### PR TITLE
Removed some deprecated Joomla Framework code.

### PR DESCRIPTION
**Pull request by dam-man**
Removed Jrequest::getVar and replaced it with Jinput.
Removed deprecated form token check and replaced it with new version of this check.
Removed Jraise Error and replaced it with Japplication one

### CODE REVIEW

**Comment by anibalsanchez** [comment]
Hi,

Thank you for submitting the PR!

I've been reviewed the code and it is mostly what it is needed to update the code.

However, why are you removing JRequest::checkToken() ?

For example, if we assume com_installer is the gold standard, then we should keep: 

		// Check for request forgeries.
		JSession::checkToken() or jexit(JText::_('JINVALID_TOKEN'));

**Comment by dam-man** [comment]
JRequest::checkToken() is deprecated 

This one is the short hand writing indeed:

// Check for request forgeries.
JSession::checkToken() or jexit(JText::_('JINVALID_TOKEN'));

So this is also OK, mine is also working but not the shorthand version.

**Comment by anibalsanchez** [comment]
Please, could you update the PR to follow the same practice followed by Joomla Core.

**Comment by dam-man** [comment]
Done

**Comment by anibalsanchez** [comment]
There's another occurrence in unzip().

**Comment by dam-man** [comment]
Has been changed also :)

**Pull request merged**
